### PR TITLE
Add linter CI pipeline

### PR DESCRIPTION
**Pull request by henrybear327**

### CODE REVIEW

**Comment by henrybear327** [comment]
The license header part is under discussion. Moving to draft state.

**Comment by henrybear327** [comment]
> The license header part is under discussion. Moving to draft state.

Splitting the license header check to https://github.com/netbox-community/netbox-operator/pull/60

**Comment by henrybear327** [comment]
Linter errors have been fixed with this PR!

**Review by alexandernorth — APPROVED** [review]
lgtm

**Review by alexandernorth — APPROVED** [review]

**Review by faebr — APPROVED** [review]

**Pull request merged**
