### PR TITLE
Add image build pipeline

### PR DESCRIPTION
**Pull request by henrybear327**
- Build docker images for both x86 and ARM architectures
- Perform image build test on PRs
- Push to ghcr.io when merged to `main`

### CODE REVIEW

**Comment by henrybear327** [comment]
Only the images of those commits that are merged into the main branch
will be available on the GitHub registry, as we don't have unlimited
storage up here [1].

The pipeline is tested at https://github.com/henrybear327/netbox-operator/pull/1.

Reference:
- https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages

**Comment by jstudler** [comment]
> Building an ARM docker image once will take around 17 minutes per run. See https://github.com/netbox-community/netbox-operator/actions/runs/10770458614/job/29863858976?pr=30
> 
> But it's a nice thing to have as we can finally run the operator on M1 natively!

Wonder if we really want to build on MRs. But we can always remove it later in case we use too much CI resources.

**Review by jstudler — APPROVED** [review]
lgtm

**Review by alexandernorth — APPROVED** [review]
lgtm

**Pull request merged**
