### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by henrybear327**
Adding `code of conduct` according to Swisscom's FOSS guideline

### CODE REVIEW

**Comment by henrybear327** [comment]
@ashanvbs @jstudler do you have an idea what to use for `[INSERT CONTACT METHOD]`? :)

**Comment by jstudler** [comment]
> @ashanvbs @jstudler do you have an idea what to use for `[INSERT CONTACT METHOD]`? :)

So either we link the GitHub profiles of some of us that have a contact method listed or abuse@swisscom.com?

**Comment by henrybear327** [comment]
Given that we are maintaining it under NetBox Org instead of under the Swisscom org now, maybe it could be either you or Ashan? What do you think?

**Comment by henrybear327** [comment]
> > @ashanvbs @jstudler do you have an idea what to use for `[INSERT CONTACT METHOD]`? :)
> 
> So either we link the GitHub profiles of some of us that have a contact method listed or [abuse@swisscom.com](mailto:abuse@swisscom.com)?

On second thought, it might be easier to use [abuse@swisscom.com](mailto:abuse@swisscom.com), as GitHub accounts don't come with a direct communication channel.

WDYT @jstudler ?

**Comment by ashanvbs** [comment]
> Given that we are maintaining it under NetBox Org instead of under the Swisscom org now, maybe it could be either you or Ashan? What do you think?

Yeah I'm in favour of adding abuse@swisscom.com. We can as well ask compliance team what we've used on other projects.

**Comment by jstudler** [comment]
> Based on the reply from the compliance team, we should probably put the maintainer's email. @jstudler @ashanvbs can I use your email?
> 
> Thanks

I cannot find this statement in the thread. I'm still in favor of abuse@swisscom.com. If we need to change it later, we can always do that.

**Comment by henrybear327** [comment]
> > Based on the reply from the compliance team, we should probably put the maintainer's email. @jstudler @ashanvbs can I use your email?
> > Thanks
> 
> I cannot find this statement in the thread. I'm still in favor of [abuse@swisscom.com](mailto:abuse@swisscom.com). If we need to change it later, we can always do that.

Email forwarded to you (sorry that I missed this). 

Let's stick with [abuse@swisscom.com](mailto:abuse@swisscom.com) :)

**Review by jstudler — APPROVED** [review]

**Pull request merged**
