### PR TITLE
Add e2e tests for Prefix

### PR DESCRIPTION
**Pull request by henrybear327**
Leveraging Chainsaw, we can easily write e2e tests for the NetBox operator, testing directly against the NetBox instance

This PR focuses solely on the Prefix and PrefixClaim, happy path.

Implements https://github.com/netbox-community/netbox-operator/issues/163

### CODE REVIEW

**Comment by henrybear327** [comment]
The happy path written are 
- apply the sample CR and see if it works
- apply -> delete -> apply and see if the restoration works

**Comment by henrybear327** [comment]
The e2e test run is consistently running around 8.5 min (https://github.com/netbox-community/netbox-operator/actions/runs/12273670479/job/34244939819?pr=161)

The main time is spent on setting things up...

**Comment by henrybear327** [comment]
@bruelea commented that we shouldn't load demo data for e2e tests, which I will address in https://github.com/netbox-community/netbox-operator/pull/164

**Comment by henrybear327** [comment]
> @bruelea commented that we shouldn't load demo data for e2e tests

This is a lot more work than expected, since we need to extract the minimal tables to set up, etc. Propose to have it done in a follow-up PR. WDYT?

Thanks

**Review by bruelea — APPROVED** [review]
Nice work! Great to be able to test against an NetBox instance in the kind cluster.

**Pull request merged**
