### PR TITLE
Restructure the controller tests

### PR DESCRIPTION
**Pull request by bruelea**
In this PR the controller tests were restructured to avoid race conditions

### CODE REVIEW

**Comment by henrybear327** [comment]
I rebased this PR on https://github.com/netbox-community/netbox-operator/pull/29 so we can see if the integration test is properly fixed!

**Comment by henrybear327** [comment]
Integration test CI is now passing!

**Comment by henrybear327** [comment]
Hey @bruelea sorry that I have no idea what happened that made this PR merged (I didn't push the button...), but it's actually not merged into the main branch (magic?)

Can you open a new PR with your branch? Thanks .. :)

**Comment by bruelea** [comment]
> Hey @bruelea sorry that I have no idea what happened that made this PR merged (I didn't push the button...), but it's actually not merged into the main branch (magic?)
> 
> Can you open a new PR with your branch? Thanks .. :)

Done. Thanks @henrybear327  for testing the PR in the pipeline!

**Pull request merged**
